export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUES";
export const USER_LOGIN_SUCESS = "USER_LOGIN_SUCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const UPDATE_MUSIC_RECORD_SUCESS = "UPDATE_MUSIC_RECORD_SUCESS";
